#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows
{
    namespace UI
    {
        namespace Xaml
        {
            namespace Controls
            {
                ref class Grid;
                ref class RowDefinition;
                ref class ColumnDefinition;
            }
        }
    }
}
namespace Windows
{
    namespace UI
    {
        namespace Xaml
        {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}
namespace CalculatorApp
{
    ref class NumberPad;
}
namespace CalculatorApp
{
    namespace Controls
    {
        ref class CalculatorButton;
    }
}

namespace CalculatorApp
{
    [::Windows::Foundation::Metadata::WebHostHidden] partial ref class CalculatorStandardOperators : public ::Windows::UI::Xaml::Controls::UserControl,
                                                                                                     public ::Windows::UI::Xaml::Markup::IComponentConnector,
                                                                                                     public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object ^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector ^ GetBindingConnector(int connectionId, ::Platform::Object ^ target);

    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject ^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);

    private:
        bool _contentLoaded;

        class CalculatorStandardOperators_obj1_Bindings;

        ::XamlBindingInfo::XamlBindings ^ Bindings;

    private:
        ::Windows::UI::Xaml::Controls::Grid ^ Root;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ R0;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ R1;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ R2;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ R3;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ R4;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ R5;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ GutterLeft;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ C0;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ C1;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ C2;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ C3;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ C4;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ GutterRight;

    private:
        ::Windows::UI::Xaml::VisualStateGroup ^ ErrorVisualStates;

    private:
        ::Windows::UI::Xaml::VisualState ^ ShowStandardFunctions;

    private:
        ::Windows::UI::Xaml::VisualState ^ HideStandardFunctions;

    private:
        ::Windows::UI::Xaml::VisualState ^ Large;

    private:
        ::Windows::UI::Xaml::VisualState ^ Medium;

    private:
        ::Windows::UI::Xaml::VisualState ^ Small;

    private:
        ::Windows::UI::Xaml::VisualState ^ Tiny;

    private:
        ::Windows::UI::Xaml::VisualState ^ NoErrorLayout;

    private:
        ::Windows::UI::Xaml::VisualState ^ ErrorLayout;

    private:
        ::Windows::UI::Xaml::Controls::Grid ^ DisplayControls;

    private:
        ::Windows::UI::Xaml::Controls::Grid ^ StandardFunctions;

    private:
        ::Windows::UI::Xaml::Controls::Grid ^ StandardOperators;

    private:
        ::CalculatorApp::NumberPad ^ NumberPad;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ NegateButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ DivideButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ MultiplyButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ MinusButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ PlusButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ EqualButton;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ FnR1;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ FnR2;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ FnR3;

    private:
        ::Windows::UI::Xaml::Controls::RowDefinition ^ FnR4;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ FnC1;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ FnC2;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ FnC3;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ InvertButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ XPower2Button;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ SquareRootButton;

    private:
        ::Windows::UI::Xaml::Controls::ColumnDefinition ^ PercentColumn;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ PercentButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ ClearEntryButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ ClearButton;

    private:
        ::CalculatorApp::Controls::CalculatorButton ^ BackSpaceButton;
    };
}
